server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user
          uri: lb://user-services
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: goods
          uri: lb://goods-services
          predicates:
            - Path=/goods/**
          filters:
            - StripPrefix=1
        - id: order
          uri: lb://order-services
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.nacos.discovery: DEBUG
