server:
  port: 8083

spring:
  application:
    name: order-services
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    openfeign:
      client:
        config:
          default:
            connect-timeout: 10000
            read-timeout: 10000
      circuitbreaker:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/platform-order?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

# Resilience4j CircuitBreaker ?????COUNT_BASED ???
#  6???????????????50%?CircuitBreaker?????OPEN??(???????)???????
#  ??5???CircuitBreaker ??????OPEN???????HALF_OPEN???????????????????????
#  ?????CircuitBreaker ???????OPEN???????????CLOSE?????????????
resilience4j:
  timelimiter:
    configs:
        default:
          timeout-duration: 5s
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50 #??50%?????????????????????CircuitBreaker??OPEN???
        slidingWindowType: COUNT_BASED # ???????
        slidingWindowSize: 6 #?????????COUNT_BASED??6??????TIME_BASED??6?
        minimumNumberOfCalls: 6 #??????????????????????(????????)???minimumNumberOfCalls?10????????10????????????????????9????????9????????????????
        automaticTransitionFromOpenToHalfOpenEnabled: true # ???????????????????????true??????CircuitBreaker????????????????????????????????????
        waitDurationInOpenState: 5s #?OPEN?HALF_OPEN?????????
        permittedNumberOfCallsInHalfOpenState: 2 #?????????????????10????????CircuitBreaker?????permittedNumberOfCallsInHalfOpenState????????????????????CircuitBreaker??????????
        recordExceptions:
          - java.lang.Exception
    instances:
      cloud-goods-service:
        baseConfig: default

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.nacos.discovery: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.cloud.circuitbreaker: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

